# calories.py
calories_dict={
    'apple': 95,
    'banana': 105,
    'beetroot': 43,
    'bell pepper': 20,
    'cabbage': 25,
    'capsicum': 31,
    'carrot': 41,
    'cauliflower': 25,
    'chilli pepper': 40,
    'corn': 86,
    'cucumber': 16,
    'eggplant': 25,
    'garlic': 149,
    'ginger': 80,
    'grapes': 67,
    'jalepeño': 27,
    'kiwi': 61,
    'lemon': 29,
    'lettuce': 15,
    'mango': 60,
    'onion': 40,
    'orange': 47,
    'paprika': 28,
    'peas': 81,
    'pear': 58,
    'pineapple': 50,
    'pomegranate': 83,
    'potato': 77,
    'raddish': 16,
    'soy bean': 173,
    'spinach': 23,
    'sweet potato': 86,
    'sweetcorn': 86,
    'tomato': 18,
    'turnip': 28,
    'watermelon': 30
}